package dao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;


public class AddressRepository {
	

		private String url = "jdbc:hsqldb:hsql://localhost/workdb";
		private Connection connection;
		private String createTableSql = 
				"CREATE TABLE address("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "number VARCHAR(20),"
				+ "nameStreet VARCHAR(50),"
				+ "postCode VARCHAR(8),"
				+ "City VARCHAR(30)"
				+ ")";
		
		Statement createTable;
		
		
		public AddressRepository(){
			
			try {
				
				connection = DriverManager.getConnection(url);
				createTable = connection.createStatement();
				createTable.executeUpdate(createTableSql);
				
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		
		
	

}
