package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import domain.Person;

public class AdresRepository {

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private Connection connection;
	private String createTableSql = 
			"CREATE TABLE person("
			+ "kodpoczt bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "miasto VARCHAR(30),"
			+ "ulica VARCHAR(50),"
			+ "kraj VARCHAR(50),"			
			+ "nrdomu int"
			+ "nrmieszk int"
			+ ")";
	
private String insertSql = "INSERT INTO adres(kodpoczt, miasto, ulica, kraj, nrdomu, nrmieszk) VALUES (?,?,?,?,?,?)";
	
	Statement createTable;
	PreparedStatement insert;
	
	public AdresRepository(){
		
	try {
			
			connection = DriverManager.getConnection(url);
			createTable = connection.createStatement();
			insert = connection.prepareStatement(insertSql);
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("Adres".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists=true;
					break;
				}
			}
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
				
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public void add(Adres p){
		try{
			insert.setString(1, p.getMiasto());
			insert.setString(2, p.getSurname());
			insert.setInt(3, p.getAge());
			insert.executeUpdate();
		}catch(SQLException ex){
			ex.printStackTrace();
		}
	}
}