package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class AdresRepository {

private String url = "jdbc:hsqldb:hsql://localhost/workdb";
private Connection connection;
private String createTableSql = 
		"CREATE TABLE Adres"
		+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
		+ "ulica VARCHAR(20),"
		+ "miasto VARCHAR(50),"
		+ "numer int"
		+ ")";

Statement createTable;


public AdresRepository(){
	
	try {
		
		connection = DriverManager.getConnection(url);
		createTable = connection.createStatement();
		createTable.executeUpdate(createTableSql);
		
	} catch (SQLException e) {
		e.printStackTrace();
	}}}

