package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import dao.mappers.IMapResultSetToEntity;
import domain.Person;

public class PersonRepository extends RepositoryBase<Person> {

	public PersonRepository(Connection connection, IMapResultSetToEntity<Person> mapper) {
		super(connection,mapper);
	}

	public void setUpdateQuery(Person p) throws SQLException {
		update.setString(1, p.getName());
		update.setString(2, p.getSurname());
		update.setInt(3, p.getAge());
		update.setInt(4, p.getId());
	}

	public void setInsertQuery(Person p) throws SQLException {
		insert.setString(1, p.getName());
		insert.setString(2, p.getSurname());
		insert.setInt(3, p.getAge());
	}

	@Override
	protected String tableName() {
		return "person";
	}

	protected String createTableSql() {
		return "CREATE TABLE person("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20)," + "surname VARCHAR(50)," + "age int"
				+ ")";
	}

	protected String insertSql() {
		return "INSERT INTO person(name, surname, age) VALUES (?,?,?)";
	}

	protected String updateSql() {
		return "UPDATE person SET name = ?, surname = ?, age = ? WHERE id = ?";
	}

}
